/// All countries with dial code (E.164 prefix). Used for phone input with country selector.
class CountryCode {
  const CountryCode({required this.name, required this.dialCode, required this.iso2});
  final String name;
  final String dialCode;
  final String iso2;
}

const List<CountryCode> countryCodes = [
  CountryCode(name: 'Peru', dialCode: '+51', iso2: 'PE'), // Default country for TransportBidder
  CountryCode(name: 'India', dialCode: '+91', iso2: 'IN'),
  CountryCode(name: 'United States', dialCode: '+1', iso2: 'US'),
  CountryCode(name: 'United Kingdom', dialCode: '+44', iso2: 'GB'),
  CountryCode(name: 'Mexico', dialCode: '+52', iso2: 'MX'),
  CountryCode(name: 'Colombia', dialCode: '+57', iso2: 'CO'),
  CountryCode(name: 'Spain', dialCode: '+34', iso2: 'ES'),
  CountryCode(name: 'Argentina', dialCode: '+54', iso2: 'AR'),
  CountryCode(name: 'Brazil', dialCode: '+55', iso2: 'BR'),
  CountryCode(name: 'Chile', dialCode: '+56', iso2: 'CL'),
  CountryCode(name: 'Ecuador', dialCode: '+593', iso2: 'EC'),
  CountryCode(name: 'France', dialCode: '+33', iso2: 'FR'),
  CountryCode(name: 'Germany', dialCode: '+49', iso2: 'DE'),
  CountryCode(name: 'Italy', dialCode: '+39', iso2: 'IT'),
  CountryCode(name: 'Russia', dialCode: '+7', iso2: 'RU'),
  CountryCode(name: 'China', dialCode: '+86', iso2: 'CN'),
  CountryCode(name: 'Japan', dialCode: '+81', iso2: 'JP'),
  CountryCode(name: 'Pakistan', dialCode: '+92', iso2: 'PK'),
  CountryCode(name: 'Bangladesh', dialCode: '+880', iso2: 'BD'),
  CountryCode(name: 'Nepal', dialCode: '+977', iso2: 'NP'),
  CountryCode(name: 'Sri Lanka', dialCode: '+94', iso2: 'LK'),
  CountryCode(name: 'Afghanistan', dialCode: '+93', iso2: 'AF'),
  CountryCode(name: 'Albania', dialCode: '+355', iso2: 'AL'),
  CountryCode(name: 'Algeria', dialCode: '+213', iso2: 'DZ'),
  CountryCode(name: 'Andorra', dialCode: '+376', iso2: 'AD'),
  CountryCode(name: 'Angola', dialCode: '+244', iso2: 'AO'),
  CountryCode(name: 'Australia', dialCode: '+61', iso2: 'AU'),
  CountryCode(name: 'Austria', dialCode: '+43', iso2: 'AT'),
  CountryCode(name: 'Azerbaijan', dialCode: '+994', iso2: 'AZ'),
  CountryCode(name: 'Bahrain', dialCode: '+973', iso2: 'BH'),
  CountryCode(name: 'Belgium', dialCode: '+32', iso2: 'BE'),
  CountryCode(name: 'Bolivia', dialCode: '+591', iso2: 'BO'),
  CountryCode(name: 'Botswana', dialCode: '+267', iso2: 'BW'),
  CountryCode(name: 'Bulgaria', dialCode: '+359', iso2: 'BG'),
  CountryCode(name: 'Canada', dialCode: '+1', iso2: 'CA'),
  CountryCode(name: 'Costa Rica', dialCode: '+506', iso2: 'CR'),
  CountryCode(name: 'Croatia', dialCode: '+385', iso2: 'HR'),
  CountryCode(name: 'Cuba', dialCode: '+53', iso2: 'CU'),
  CountryCode(name: 'Cyprus', dialCode: '+357', iso2: 'CY'),
  CountryCode(name: 'Czech Republic', dialCode: '+420', iso2: 'CZ'),
  CountryCode(name: 'Denmark', dialCode: '+45', iso2: 'DK'),
  CountryCode(name: 'Egypt', dialCode: '+20', iso2: 'EG'),
  CountryCode(name: 'Estonia', dialCode: '+372', iso2: 'EE'),
  CountryCode(name: 'Ethiopia', dialCode: '+251', iso2: 'ET'),
  CountryCode(name: 'Finland', dialCode: '+358', iso2: 'FI'),
  CountryCode(name: 'Ghana', dialCode: '+233', iso2: 'GH'),
  CountryCode(name: 'Greece', dialCode: '+30', iso2: 'GR'),
  CountryCode(name: 'Guatemala', dialCode: '+502', iso2: 'GT'),
  CountryCode(name: 'Hong Kong', dialCode: '+852', iso2: 'HK'),
  CountryCode(name: 'Hungary', dialCode: '+36', iso2: 'HU'),
  CountryCode(name: 'Indonesia', dialCode: '+62', iso2: 'ID'),
  CountryCode(name: 'Iran', dialCode: '+98', iso2: 'IR'),
  CountryCode(name: 'Iraq', dialCode: '+964', iso2: 'IQ'),
  CountryCode(name: 'Ireland', dialCode: '+353', iso2: 'IE'),
  CountryCode(name: 'Israel', dialCode: '+972', iso2: 'IL'),
  CountryCode(name: 'Jordan', dialCode: '+962', iso2: 'JO'),
  CountryCode(name: 'Kazakhstan', dialCode: '+7', iso2: 'KZ'),
  CountryCode(name: 'Kenya', dialCode: '+254', iso2: 'KE'),
  CountryCode(name: 'Kuwait', dialCode: '+965', iso2: 'KW'),
  CountryCode(name: 'Lebanon', dialCode: '+961', iso2: 'LB'),
  CountryCode(name: 'Malaysia', dialCode: '+60', iso2: 'MY'),
  CountryCode(name: 'Morocco', dialCode: '+212', iso2: 'MA'),
  CountryCode(name: 'Netherlands', dialCode: '+31', iso2: 'NL'),
  CountryCode(name: 'New Zealand', dialCode: '+64', iso2: 'NZ'),
  CountryCode(name: 'Nigeria', dialCode: '+234', iso2: 'NG'),
  CountryCode(name: 'Norway', dialCode: '+47', iso2: 'NO'),
  CountryCode(name: 'Oman', dialCode: '+968', iso2: 'OM'),
  CountryCode(name: 'Philippines', dialCode: '+63', iso2: 'PH'),
  CountryCode(name: 'Poland', dialCode: '+48', iso2: 'PL'),
  CountryCode(name: 'Portugal', dialCode: '+351', iso2: 'PT'),
  CountryCode(name: 'Qatar', dialCode: '+974', iso2: 'QA'),
  CountryCode(name: 'Romania', dialCode: '+40', iso2: 'RO'),
  CountryCode(name: 'Saudi Arabia', dialCode: '+966', iso2: 'SA'),
  CountryCode(name: 'Singapore', dialCode: '+65', iso2: 'SG'),
  CountryCode(name: 'South Africa', dialCode: '+27', iso2: 'ZA'),
  CountryCode(name: 'South Korea', dialCode: '+82', iso2: 'KR'),
  CountryCode(name: 'Sweden', dialCode: '+46', iso2: 'SE'),
  CountryCode(name: 'Switzerland', dialCode: '+41', iso2: 'CH'),
  CountryCode(name: 'Taiwan', dialCode: '+886', iso2: 'TW'),
  CountryCode(name: 'Thailand', dialCode: '+66', iso2: 'TH'),
  CountryCode(name: 'Turkey', dialCode: '+90', iso2: 'TR'),
  CountryCode(name: 'Ukraine', dialCode: '+380', iso2: 'UA'),
  CountryCode(name: 'UAE', dialCode: '+971', iso2: 'AE'),
  CountryCode(name: 'Uruguay', dialCode: '+598', iso2: 'UY'),
  CountryCode(name: 'Venezuela', dialCode: '+58', iso2: 'VE'),
  CountryCode(name: 'Vietnam', dialCode: '+84', iso2: 'VN'),
  CountryCode(name: 'Zimbabwe', dialCode: '+263', iso2: 'ZW'),
];
