// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANVtoHKjRUkXduTEhMKKOVQNGrslinPME',
    appId: '1:327333558755:web:34c80c5b2aaa41c53108d6',
    messagingSenderId: '327333558755',
    projectId: 'transport-bidder',
    authDomain: 'transport-bidder.firebaseapp.com',
    storageBucket: 'transport-bidder.firebasestorage.app',
    measurementId: 'G-SLYGMEL42N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsHLNY-HVmu7eZ-F_PyEvTy6orSrLP8Z8',
    appId: '1:327333558755:android:4cb5bcdc9c14ddbd3108d6',
    messagingSenderId: '327333558755',
    projectId: 'transport-bidder',
    storageBucket: 'transport-bidder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk_wcBITaWbvEDS8he2YGCni84t3E--Rg',
    appId: '1:327333558755:ios:8eae09e574999fa23108d6',
    messagingSenderId: '327333558755',
    projectId: 'transport-bidder',
    storageBucket: 'transport-bidder.firebasestorage.app',
    iosBundleId: 'com.tbidder.tbidderUserApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk_wcBITaWbvEDS8he2YGCni84t3E--Rg',
    appId: '1:327333558755:ios:8eae09e574999fa23108d6',
    messagingSenderId: '327333558755',
    projectId: 'transport-bidder',
    storageBucket: 'transport-bidder.firebasestorage.app',
    iosBundleId: 'com.tbidder.tbidderUserApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANVtoHKjRUkXduTEhMKKOVQNGrslinPME',
    appId: '1:327333558755:web:30b4957b7344dfcc3108d6',
    messagingSenderId: '327333558755',
    projectId: 'transport-bidder',
    authDomain: 'transport-bidder.firebaseapp.com',
    storageBucket: 'transport-bidder.firebasestorage.app',
    measurementId: 'G-CWXN1838GL',
  );
}
